### ISSUE TITLE
Convert the site to a Kontent template

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-sample-blog-travel-vue#8]
### Motivation

Be able to easily spin up the project using [Kontent template manager](https://kentico.github.io/kontent-template-manager/).

### Proposed solution

Use the following steps: https://github.com/Kentico/kontent-template-manager/blob/master/README.md#submitting-web-template-to-templates-gallery

Related to: https://github.com/Kentico/kontent-template-manager/pull/41

**Comment by Simply007** [comment]
https://github.com/Kentico/kontent-template-manager/pull/43
